# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='data',
        ),
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(default='image_name', max_length=200),
            preserve_default=False,
        ),
    ]
