# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-10 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0002_auto_20160310_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='needed_stuff',
            field=models.CharField(default='None', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='xp_type',
            field=models.CharField(default='Not Defined', max_length=200),
            preserve_default=False,
        ),
    ]
