# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-11 18:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wheel', '0003_auto_20160310_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creator_link',
            new_name='creator_url',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_link',
            new_name='project_url',
        ),
    ]
